[Simple1]
[Simple1.structure]
layers = [
  { type = "Conv2D", filters = 8, kernel_size = [3, 1], activation = "relu" },
  { type = "MaxPooling2D", pool_size = [2, 1] },
  { type = "Flatten" },
  { type = "Dense", units = 8, activation = "relu" },
  { type = "Dense", units = 12, activation = "linear" }
]
[Simple1.compile]
optimizer = "sgd"  # Simpler optimizer
loss = "mean_squared_error"
metrics = ["R_squared", "MeanSquaredError", "MeanAbsoluteError", "MeanAbsolutePercentageError", "RootMeanSquaredError"]
[Simple1.dataset]
id = "d1"
[Simple1.training]
epochs = 40



[Simple2]
[Simple2.structure]
layers = [
  { type = "Conv2D", filters = 16, kernel_size = [3, 1], activation = "relu" },
  { type = "Flatten" },
  { type = "Dense", units = 12, activation = "linear" }
]
[Simple2.compile]
optimizer = "sgd"
loss = "mean_squared_error"
metrics = ["R_squared", "MeanSquaredError", "MeanAbsoluteError", "MeanAbsolutePercentageError", "RootMeanSquaredError"]
[Simple2.dataset]
id = "d1"
[Simple2.training]
epochs = 40


[Simple3]
[Simple3.structure]
layers = [
  { type = "Flatten" },
  { type = "Dense", units = 32, activation = "relu" },
  { type = "Dense", units = 12, activation = "linear" }
]
[Simple3.compile]
optimizer = "sgd"
loss = "mean_squared_error"
metrics = ["R_squared", "MeanSquaredError", "MeanAbsoluteError", "MeanAbsolutePercentageError", "RootMeanSquaredError"]
[Simple3.dataset]
id = "d1"
[Simple3.training]
epochs = 40


