
[Simple1]
[Simple1.structure]
layers = [
  { type = "Conv2D", filters = 8, kernel_size = [3, 1], activation = "relu" },
  { type = "MaxPooling2D", pool_size = [2, 1] },
  { type = "Flatten" },
  { type = "Dense", units = 8, activation = "relu" },
  { type = "Dense", units = 12, activation = "linear" }
]
[Simple1.compile]
optimizer = "sgd"  # Simpler optimizer
loss = "mean_squared_error"
metrics = ["MeanSquaredError"]
[Simple1.dataset]
shuffle_buffer_size = 512  # Reduced buffer size
batch_size = 32  # Smaller batch size
splits = [0.7, 0.15, 0.15]
[Simple1.training]
epochs = 1



[Simple2]
[Simple2.structure]
layers = [
  { type = "Conv2D", filters = 16, kernel_size = [3, 1], activation = "relu" },
  { type = "Flatten" },
  { type = "Dense", units = 12, activation = "linear" }
]
[Simple2.compile]
optimizer = "sgd"
loss = "mean_squared_error"
metrics = ["MeanSquaredError"]
[Simple2.dataset]
shuffle_buffer_size = 512
batch_size = 32
splits = [0.7, 0.15, 0.15]
[Simple2.training]
epochs = 1

